# Generated by Django 3.2 on 2021-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'chat', 'verbose_name_plural': 'chat'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'message', 'verbose_name_plural': 'message'},
        ),
    ]
