# Generated by Django 3.2 on 2021-11-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utills.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uuid', utills.uuid.CustomUUIDField(blank=True, editable=False, max_length=10, unique=True)),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('list_price', models.PositiveIntegerField(verbose_name='price')),
                ('share_doctor', models.FloatField(verbose_name='share_doctor')),
                ('share_employee', models.PositiveIntegerField(verbose_name='share_employee')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uuid', utills.uuid.CustomUUIDField(blank=True, editable=False, max_length=10, unique=True)),
                ('treatment_time', models.DateTimeField(null=True, verbose_name='treatment schedule')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('next_treatement', models.CharField(blank=True, max_length=250, null=True, verbose_name='next_treatment')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='diagnosis')),
                ('employee', models.CharField(blank=True, max_length=200, null=True, verbose_name='payed_man')),
                ('paid_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid_amount')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('TR', 'Treated'), ('CO', 'Confirmed'), ('PA', 'Paied')], default='CR', max_length=50)),
                ('branch', models.CharField(choices=[('SURABAYA', 'SURABAYA'), ('LOCATION2', 'LOCATION2')], default=None, max_length=50, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoice/2021-11/', verbose_name='invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='docotr')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uuid', utills.uuid.CustomUUIDField(blank=True, editable=False, max_length=10, unique=True)),
                ('teeth', models.CharField(max_length=50, verbose_name='teeth')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='qantity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.service', verbose_name='service')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
