# Generated by Django 3.2 on 2021-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid_amount'),
        ),
    ]
