# Generated by Django 3.2 on 2021-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_treatment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='paid_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid amount'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('TR', 'Treated'), ('PA', 'Paied')], default='CR', max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='total amount'),
        ),
    ]
