# Generated by Django 3.2 on 2021-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_alter_treatment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Treated', 'Treated'), ('Paying', 'Paying'), ('Paid', 'Paid')], default='Created', max_length=50),
        ),
    ]
