# Generated by Django 3.2 on 2021-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_auto_20211120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/2021-12/', verbose_name='invoice'),
        ),
    ]
