# Generated by Django 3.2 on 2021-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_alter_treatment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Treated', 'Treated'), ('Confirmed', 'Comfirmed'), ('Paid', 'Paid')], default='Created', max_length=50),
        ),
    ]
