# Generated by Django 3.2.9 on 2022-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0010_alter_treatment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('-treatment_time',), 'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatment'},
        ),
        migrations.AlterField(
            model_name='treatment',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/2022-02/', verbose_name='invoice'),
        ),
    ]
