# Generated by Django 3.2 on 2021-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'gruop', 'verbose_name_plural': 'gruop'},
        ),
    ]
