# Generated by Django 3.2 on 2021-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('SURABAYA', 'SURABAYA'), ('LOCATION2', 'LOCATION2')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Employee', 'Employee')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
