# Generated by Django 3.2 on 2021-11-12 15:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICF001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('ga_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ga_id')),
                ('q1', models.CharField(max_length=50, verbose_name='Nama lengkap calon pasien')),
                ('q2', models.CharField(max_length=50, verbose_name='Nomor HP/ Whatsapp calon pasien')),
                ('q7', models.CharField(max_length=50, verbose_name='Email calon pasien')),
                ('q3', models.CharField(max_length=50, verbose_name='Alamat domisili calon pasien')),
                ('q4', models.CharField(max_length=50, verbose_name='Pekerjaan calon pasien')),
                ('q5', models.CharField(max_length=50, verbose_name='Tempat dan tanggal lahir calon pasien')),
                ('q6', multiselectfield.db.fields.MultiSelectField(choices=[('Rekomendasi Teman/Keluarga/Kenalan', 'Rekomendasi Teman/Keluarga/Kenalan'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('lainnya', 'lainnya')], max_length=50, verbose_name='Dari manakah Anda tahu Indental Clinic? (Mohon pilih salah satu)')),
                ('q6_other', models.CharField(blank=True, max_length=50, null=True, verbose_name="Jika Anda memilih 'lainnya', tolong tuliskan jawaban Anda di bawah")),
            ],
            options={
                'verbose_name': 'Form_N01',
                'verbose_name_plural': 'Form_N01',
            },
        ),
        migrations.CreateModel(
            name='ICF002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=20, verbose_name='Nama')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('service', models.CharField(choices=[('KO', 'Konsultasi (Mulai dari Rp 200.000)'), ('KA', 'Kawat Gigi (Mulai dari Rp 10.00.000)'), ('SC', 'Scaling Gigi (Mulai dari Rp 300.000)'), ('PE', 'Pemutihan Gigi (Mulai dari Rp 1.750.000)'), ('BE', 'Bedah Mulut (Mulai dari Rp 400.000)'), ('PE', 'Pembersihan Gigi (Mulai dari Rp 250.000)'), ('CA', 'Cabut Gigi (Mulai dari Rp 300.000)'), ('PE', 'Pemasangan Crown Gigi (Mulai dari Rp 2.500.000)'), ('GI', 'Gigi Palsu (Mulai dari Rp 1.000.000)'), ('VE', 'Veneer Gigi (Mulai dari Rp 800.000)'), ('TA', 'Tambal Gigi (Mulai dari Rp 350.000)'), ('IM', 'Implan Gigi (Mulai dari Rp 16.000.000)')], max_length=5, verbose_name='Layanan')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
            ],
            options={
                'verbose_name': 'ICF002',
                'verbose_name_plural': 'ICF002',
            },
        ),
        migrations.CreateModel(
            name='IFC001_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('q1', models.CharField(max_length=250, verbose_name='Pada tanggal berapa dan hari apa Anda berencana melakukan perawatan/ konsultasi ke Indental Clinic?')),
                ('q2', models.CharField(choices=[('Konsultasi', 'Konsultasi'), ('Kontrol ortodonti', 'Kontrol ortodonti'), ('Tambai gigi', 'Tambai gigi'), ('Scaling', 'Scaling'), ('Lainnya', 'Lainnya')], max_length=50, verbose_name='Perawatan apa yang rencananya hendak Anda lakukan di Indental Clinic?')),
                ('q2_other', models.CharField(blank=True, max_length=50, null=True, verbose_name="Jika Anda memilih 'lainnya', tolong tuliskan jawaban Anda di bawah")),
                ('q3', models.TextField(help_text='yes=true, no=false', verbose_name='Mohon berikan penjelasan singkat tentang keluhan yang Anda alami. Misalnya: Gigi bagian mana yang terasa sakit? Bagaimana keluhan sakitnya? Apakah terasa nyeri atau ngilu ketika makan?')),
                ('q4', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda mengalami demam >38° C dalam kurun waktu 14 hari terakhir?')),
                ('q5', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda mengalami batuk/ pilek/ nyeri tenggorokan dalam kurun waktu 14 hari terakhir?')),
                ('q6', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda mengalami sesak napas dalam kurun waktu 14 hari terakhir?')),
                ('q7', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah anda mengalami anosmia ( indera penciuman berkurang) dalam kurun 14 hari terakhir? ')),
                ('q8', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah anda mengalami diare / mual / muntah / nyeri perut dalam kurun 14 hari terakhir? ')),
                ('q9', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda bekerja atau mengunjungi fasilitas kesehatan yang berhubungan dengan kasus pasien konfirmasi COVID-19?')),
                ('q10', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda bekerja atau menghadiri perkumpulan massal/tempat ibadah/arisan/pesta/pasar atau tempat jasa (bandara, bank, dll)?')),
                ('q11', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah keluarga Anda (1 rumah) bekerja atau bepergian ke tempat dengan kasus positif/berisiko?')),
                ('q12', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah lingkungan sekitar Anda didapatkan kasus konfirmasi COVID-19 (tempat tinggal atau tempat kerja)?')),
                ('q13', models.BooleanField(choices=[(True, 'IYA'), (False, 'TIDAK')], default=False, verbose_name='Apakah Anda pernah melakukan tes COVID-19 sebelumnya?')),
                ('q14', models.DateField(null=True, verbose_name='Jika ya, kapan Anda melakukan tes tersebut?')),
                ('q15', models.BooleanField(choices=[(True, 'Reaktif'), (False, 'Non-reaktif')], default=False, verbose_name='Jika ya, apa hasil dari rapid test COVID-19 Anda?')),
                ('q16', models.BooleanField(choices=[(True, 'Positif'), (False, 'Negatif')], default=False, verbose_name='Jika ya, apa hasil dari tes swab COVID-19 Anda?')),
                ('q17', multiselectfield.db.fields.MultiSelectField(choices=[('A1', 'Mengisi formulir ini dengan lengkap dan sebenar-benarnya, paling lambat satu hari sebelum pasien datang ke Indental Clinic'), ('A2', 'Memakai masker selama berada di area Indental Clinic'), ('A3', 'Ketika tiba dan sebelum melakukan perawatan di Indental Clinic, pasien dimohon untuk mencuci tangan (sesuai panduan WHO) di wastafel yang tersedia di klinik'), ('A4', 'Bagi para pengantar, dimohon untuk menunggu di ruang tunggu dan tidak masuk ke ruang perawatan (kecuali untuk pasien anak-anak)'), ('A6', 'Sebelum memulai prosedur perawatan, pasien diharapkan untuk berkumur dengan betadine yang telah disediakan di dental unit selama 20-30 detik')], max_length=50, verbose_name='Demi keselamatan dan kesehatan bersama, saya bersedia melakukan hal-hal di bawah ini ketika saya melakukan perawatan di Indental Clinic (mohon untuk memberi tanda centang)')),
                ('origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.icf001', verbose_name='1페이지')),
            ],
            options={
                'verbose_name': 'Form_N02',
                'verbose_name_plural': 'Form_N02',
            },
        ),
    ]
