# Generated by Django 3.2 on 2021-11-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontogram',
            name='date',
        ),
    ]
