# Generated by Django 3.2 on 2021-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_odontogram_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='odontogram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='odontogram',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
    ]
