# Generated by Django 3.2 on 2021-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20211120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='occupation'),
        ),
    ]
