# Generated by Django 3.2 on 2021-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmtalklog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='alarmtalklog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='phonelog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='phonelog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='pushlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='pushlog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
    ]
