from django.forms import ModelForm, TextInput, DateInput,Select, CheckboxSelectMultiple
from .models import Patient, Discount, Odontogram


class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ('name','blood_type','gender', 'address', 'birth_date','birth_place', 'occupation', 'mobile','discount_set')
        widgets = {
            'name': TextInput(attrs={"class": "form-control"}),
            'birth_date': DateInput(attrs={"placeholder":'ex) 2021-05-28',"class": "form-control", "type":"date"}),
            'birth_place': TextInput(attrs={"class": "form-control"}),
            'mobile': TextInput(attrs={"class": "form-control"}),
            'address': TextInput(attrs={"class": "form-control"}),
            'blood_type': Select(attrs={"class": "form-control"}),
            'gender': Select(attrs={"class": "form-control"}),
            'occupation': TextInput(attrs={"class": "form-control"}),
            'discount_set': CheckboxSelectMultiple(attrs={"class": "indetal"}),
        }
    
        
    def __init__(self, *args, **kwargs):
        
        super(PatientForm, self).__init__(*args, **kwargs)
    
        self.fields["discount_set"].queryset = Discount.objects.all()


class OdontogramForm(ModelForm):
    class Meta:
        model = Odontogram
        fields = (
            't_11_1', 't_11_2', 't_11_3', 't_12_1', 't_12_2', 't_12_3', 't_13_1', 't_13_2', 't_13_3', 't_14_1', 't_14_2', 't_14_3', 't_15_1', 't_15_2', 't_15_3', 't_16_1', 't_16_2', 't_16_3', 't_17_1', 't_17_2', 't_17_3', 't_18_1', 't_18_2', 't_18_3', 't_21_1', 't_21_2', 't_21_3', 't_22_1', 't_22_2', 't_22_3', 't_23_1', 't_23_2', 't_23_3', 't_24_1', 't_24_2', 't_24_3', 't_25_1', 't_25_2', 't_25_3', 't_26_1', 't_26_2', 't_26_3', 't_27_1', 't_27_2', 't_27_3', 't_28_1', 't_28_2', 't_28_3', 't_31_1', 't_31_2', 't_31_3', 't_32_1', 't_32_2', 't_32_3', 't_33_1', 't_33_2', 't_33_3', 't_34_1', 't_34_2', 't_34_3', 't_35_1', 't_35_2', 't_35_3', 't_36_1', 't_36_2', 't_36_3', 't_37_1', 't_37_2', 't_37_3', 't_38_1', 't_38_2', 't_38_3', 't_41_1', 't_41_2', 't_41_3', 't_42_1', 't_42_2', 't_42_3', 't_43_1', 't_43_2', 't_43_3', 't_44_1', 't_44_2', 't_44_3', 't_45_1', 't_45_2', 't_45_3', 't_46_1', 't_46_2', 't_46_3', 't_47_1', 't_47_2', 't_47_3', 't_48_1', 't_48_2', 't_48_3', 't_51_1', 't_51_2', 't_51_3', 't_52_1', 't_52_2', 't_52_3', 't_53_1', 't_53_2', 't_53_3', 't_54_1', 't_54_2', 't_54_3', 't_55_1', 't_55_2', 't_55_3', 't_61_1', 't_61_2', 't_61_3', 't_62_1', 't_62_2', 't_62_3', 't_63_1', 't_63_2', 't_63_3', 't_64_1', 't_64_2', 't_64_3', 't_65_1', 't_65_2', 't_65_3', 't_71_1', 't_71_2', 't_71_3', 't_72_1', 't_72_2', 't_72_3', 't_73_1', 't_73_2', 't_73_3', 't_74_1', 't_74_2', 't_74_3', 't_75_1', 't_75_2', 't_75_3', 't_81_1', 't_81_2', 't_81_3', 't_82_1', 't_82_2', 't_82_3', 't_83_1', 't_83_2', 't_83_3', 't_84_1', 't_84_2', 't_84_3', 't_85_1', 't_85_2', 't_85_3')
        widgets = {
            't_11_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_11_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_11_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_12_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_12_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_12_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_13_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_13_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_13_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_14_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_14_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_14_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_15_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_15_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_15_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_16_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_16_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_16_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_17_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_17_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_17_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_18_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_18_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_18_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_21_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_21_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_21_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_22_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_22_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_22_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_23_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_23_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_23_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_24_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_24_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_24_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_25_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_25_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_25_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_26_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_26_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_26_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_27_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_27_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_27_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_28_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_28_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_28_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_31_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_31_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_31_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_32_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_32_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_32_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_33_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_33_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_33_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_34_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_34_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_34_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_35_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_35_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_35_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_36_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_36_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_36_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_37_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_37_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_37_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_38_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_38_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_38_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_41_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_41_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_41_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_42_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_42_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_42_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_43_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_43_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_43_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_44_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_44_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_44_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_45_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_45_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_45_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_46_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_46_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_46_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_47_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_47_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_47_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_48_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_48_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_48_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_51_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_51_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_51_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_52_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_52_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_52_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_53_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_53_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_53_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_54_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_54_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_54_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_55_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_55_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_55_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_61_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_61_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_61_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_62_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_62_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_62_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_63_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_63_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_63_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_64_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_64_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_64_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_65_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_65_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_65_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_71_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_71_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_71_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_72_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_72_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_72_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_73_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_73_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_73_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_74_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_74_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_74_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_75_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_75_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_75_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_81_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_81_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_81_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_82_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_82_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_82_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_83_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_83_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_83_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_84_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_84_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_84_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_85_1': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_85_2': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            't_85_3': Select(attrs={"class": "form-control teeth-select form-control-sm p-1"}),
            }
           

    def __init__(self, *args, **kwargs):
        super(OdontogramForm, self).__init__(*args, **kwargs)
    