# Generated by Django 3.2 on 2021-12-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='cost',
            field=models.PositiveIntegerField(default=1, verbose_name='cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procurement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessory.supplier', verbose_name='supplier'),
        ),
    ]
