# Generated by Django 3.2 on 2021-11-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('pay_method', models.CharField(blank=True, choices=[(None, 'NONE'), ('CAS', 'Cash'), ('CRE', 'Credit Card'), ('BT1', 'Bank Transfer 1'), ('BT2', 'Bank Transfer 2')], default=None, max_length=50, null=True)),
                ('paid_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid_amount')),
                ('created_date', models.DateField(auto_now=True, verbose_name='created date')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
