# Generated by Django 3.2 on 2021-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(choices=[('CAS', 'Cash'), ('CRE', 'Credit Card'), ('BT1', 'Bank Transfer 1'), ('BT2', 'Bank Transfer 2')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
