# Generated by Django 3.2 on 2021-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211116_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer 1', 'Bank Transfer 1'), ('Bank Transfer 2', 'Bank Transfer 2')], max_length=50),
        ),
    ]
