# Generated by Django 3.2 on 2021-12-12 13:22

from django.db import migrations
import utills.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20211120_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=utills.uuid.CustomUUIDField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
