# Generated by Django 3.2 on 2021-12-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
    ]
