# Generated by Django 3.2.9 on 2022-02-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-treatment__treatment_time',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
    ]
