# Generated by Django 3.2 on 2021-11-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utills.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('uuid', utills.uuid.CustomUUIDField(blank=True, editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='created', max_length=50, verbose_name='status')),
                ('pdf', models.FileField(blank=True, upload_to='payslip/2021/', verbose_name='payslip pdf')),
                ('basic_salary', models.PositiveIntegerField(verbose_name='basic salary')),
                ('pay_slip_date', models.DateField(null=True, verbose_name='급여 기준일')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='modified date')),
                ('gross', models.PositiveIntegerField(blank=True, default=0, verbose_name='gross')),
                ('type', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Employee', 'Employee')], default=None, max_length=50, null=True)),
                ('noon_shift', models.PositiveIntegerField(blank=True, default=0, help_text='for doctors', verbose_name='noon shift')),
                ('overtime', models.PositiveIntegerField(blank=True, default=0, help_text='for nurses', verbose_name='overtime')),
                ('reward', models.PositiveIntegerField(blank=True, default=0, help_text='for employees', verbose_name='reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'PaySlip',
                'verbose_name_plural': 'PaySlip',
            },
        ),
    ]
