# Generated by Django 3.2.9 on 2022-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_auto_20211120_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='assistant_fee',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='for nurses', verbose_name='overtime'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pdf',
            field=models.FileField(blank=True, upload_to='payslip/2022/', verbose_name='payslip pdf'),
        ),
    ]
