name: Deploy Staging
on:
  push:
    branches:
      - staging

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Change DJANGO_SETTINGS_MODULE
        run: sed -i "s/config[.]settings.*/config.settings.stag/g" .ebextensions/01django.config

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: django-init
          environment_name: django-init-stag
          version_label: ${{ github.sha }}
          region: ap-northeast-1
          deployment_package: deploy.zip
